[build]
publish = "public"
command = "hugo --gc --minify"
ignore = "(exit 1)"

[build.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[plugins]]
package = "../"
  [plugins.inputs]
  debug = true
  srcdir = "path/to/website"

[[plugins]]
package = "@netlify/plugin-local-install-core"
