[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.74.3"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"

[[plugins]]
package = "../"
  [plugins.inputs]
  debug = true

[[plugins]]
package = "@netlify/plugin-local-install-core"
